language: node_js
node_js:
  - "7.9.0"
services:
  - docker
install:
  - npm install
  - docker pull zixia/wechaty
  - docker run -d -p 127.0.0.1:80:80 
  - docker run -ti --volume="$(pwd)":/bot --rm zixia/wechaty src/index.ts
script:
  - docker ps | grep -q wechat
