language: node_js
node_js:
  - "7.9.0"
services:
  - docker
install:
  - npm install
  - docker pull zixia/wechaty:onbuild
# script:
#   - ./startup.sh
#   - docker ps | grep -q wechat
before_install:
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv -in travis.enc -out travis -d
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/travis # this key should have push access
  - ssh-add .travis/travis
  - git remote add deploy ssh://root@47.92.88.211/root/wechat-bot-service
  - git push deploy
